import "./style.css";

const TYPES = [
    ["process", "Process", "▭", "#dbeafe"], ["start_end", "Start / End", "⬭", "#dcfce7"],
    ["decision", "Decision", "◇", "#fef3c7"], ["input_output", "Input / Output", "▱", "#fce7f3"],
    ["document", "Document", "▱", "#ede9fe"], ["multi_document", "Multiple Documents", "▤", "#e0e7ff"],
    ["subroutine", "Subroutine", "▣", "#cffafe"], ["database", "Database", "⛁", "#ffedd5"],
    ["manual_input", "Manual Input", "⌁", "#f3e8ff"], ["preparation", "Preparation", "⬟", "#ccfbf1"],
    ["connector", "Connector", "●", "#fee2e2"], ["merge", "Merge", "◇", "#fef9c3"],
    ["sort", "Sort", "▱", "#e2e8f0"], ["collate", "Collate", "▱", "#f1f5f9"],
    ["data_store", "Data Storage", "⛁", "#d1fae5"], ["delay", "Delay", "◖", "#fce7f3"],
    ["display", "Display", "▭", "#dbeafe"], ["off_page", "Off Page", "⬟", "#e0f2fe"]];
const TYPE = {}; TYPES.forEach(x => TYPE[x[0]] = { name: x[1], icon: x[2], color: x[3] });
const S = { nodes: [], edges: [], selNode: null, selEdge: null, mode: "select", dir: "TB", zoom: 1, panX: 0, panY: 0, next: 0, drag: null, connect: null, dark: false };
const app = document.querySelector("#app");
app.innerHTML = `<header><div class="brand"><b>Ｍ</b><div><strong>Mermaid Flow Designer</strong><small>Visual Mermaid flowchart editor</small><small class="disclaimer">Do not upload sensitive documents or PII.</small></div></div><div class="actions"><button id="new">New</button><label class="file">Open .md<input id="open" type="file" accept=".md,.txt" hidden></label><button id="md">Export .md</button><button id="svg">Export SVG</button><button id="png">Export PNG</button><button id="theme">☾</button><button id="help">?</button></div></header>
<main><aside class="left"><section><h3>Elements</h3><div id="palette"></div><small>Drag an element onto the canvas.</small></section><section id="props"><h3>Properties</h3><p>Select a node or arrow.</p></section></aside>
<section class="center"><nav><button class="mode active" data-mode="select">↖ Select</button><button class="mode" data-mode="connect">↗ Connect</button><select id="dir"><option value="TB">Top → Bottom</option><option value="LR">Left → Right</option><option value="BT">Bottom → Top</option><option value="RL">Right → Left</option></select><button id="layout">Auto Layout</button><button id="snap">Snap</button><span class="spacer"></span><button id="minus">−</button><span id="zoom">100%</span><button id="plus">+</button><button id="fit">Fit</button></nav>
<div id="wrap"><svg id="svg"><defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="currentColor" stroke-opacity=".1"/></pattern><marker id="arr" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10z"/></marker><marker id="arrs" viewBox="0 0 10 10" refX="1" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M10 0L0 5L10 10z"/></marker></defs><rect class="grid" x="-5000" y="-5000" width="10000" height="10000"/><g id="view"><g id="edges"/><g id="nodes"/><g id="preview"/></g></svg><div id="empty"><b>◇</b><h2>Build your diagram</h2><p>Drag an element onto the canvas.</p></div></div></section>
<aside class="right"><section><h3>Mermaid Markdown <button id="copy">Copy</button></h3><textarea id="code"></textarea></section></aside></main><div id="toast"></div><dialog id="helpBox"><h2>Controls</h2><p>Drag shapes onto the canvas. Drag nodes to move them. Choose <b>Connect</b> and drag between nodes to create an arrow.</p><p>Select an arrow to edit its label, direction and style. Delete removes the selected object. Ctrl/Cmd+D duplicates nodes.</p><button onclick="helpBox.close()">Close</button></dialog>`;
const $ = id => document.getElementById(id), svg = document.querySelector("svg#svg"), view = $("view"), nodesEl = $("nodes"), edgesEl = $("edges"), preview = $("preview"), code = $("code"), props = $("props");
function esc(s) { return String(s ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "<br/>") }
function id() { let n = S.next++, r = ""; do { r = String.fromCharCode(65 + n % 26) + r; n = Math.floor(n / 26) - 1 } while (n >= 0); return r }
function size() { return { w: 140, h: 70 } }
function edgePoint(n, targetX, targetY) { let { w, h } = size(), dx = targetX - n.x, dy = targetY - n.y; if (!dx && !dy) return [n.x, n.y]; let scale = Math.max(Math.abs(dx) / (w / 2), Math.abs(dy) / (h / 2)); return [n.x + dx / scale, n.y + dy / scale] }
function nodeDef(n) {
    let l = esc(n.label); switch (n.shape) {
        case "start_end": return `${n.id}(["${l}"])`; case "decision": case "merge": return `${n.id}{"${l}"}`;
        case "input_output": return `${n.id}[/"${l}"/]`; case "subroutine": return `${n.id}[["${l}"]]`;
        case "database": case "data_store": return `${n.id}[("${l}")]`; case "manual_input": return `${n.id}[/${l}/]`;
        case "connector": return `${n.id}(("${l}"))`; case "document": return `${n.id}>"${l}"]`;
        default: return `${n.id}["${l}"]`
    }
}
function arrow(e) { let k = e.dir + ":" + e.style; return { forward: { solid: "-->", dashed: "-.->", dotted: "-..->", thick: "==>" }, backward: { solid: "<--", dashed: "<-. -".replace(" ", ""), dotted: "<..-", thick: "<==" }, both: { solid: "<-->", dashed: "<-.->", dotted: "<..->", thick: "<==>" }, none: { solid: "---", dashed: "-.-", dotted: "-..", thick: "===" } }[e.dir][e.style] }
function mermaid() { let a = [`flowchart ${S.dir}`]; S.nodes.forEach(n => a.push(`    ${nodeDef(n)}`)); S.edges.forEach(e => a.push(`    ${e.source} ${arrow(e)}${e.label ? `|${esc(e.label)}|` : ""} ${e.target}`)); S.nodes.forEach(n => a.push(`    style ${n.id} fill:${n.color},stroke:#334155,color:${n.textColor}`)); return a.join("\n") }
function markdown() { return `# Mermaid Diagram\n\n\`\`\`mermaid\n${mermaid()}\n\`\`\`\n` }
function pt(x, y) { let r = svg.getBoundingClientRect(); return { x: (x - r.left - S.panX) / S.zoom, y: (y - r.top - S.panY) / S.zoom } }
function shape(g, n) {
    let { w, h } = size(), x = -w / 2, y = -h / 2, q;
    const el = (tag) => document.createElementNS("http://www.w3.org/2000/svg", tag);
    if (n.shape === "decision" || n.shape === "merge") { q = el("polygon"); q.setAttribute("points", `0,${y} ${w / 2},0 0,${h / 2} ${-w / 2},0`) }
    else if (n.shape === "connector") { q = el("circle"); q.setAttribute("r", 30) }
    else if (n.shape === "start_end") { q = el("rect"); q.setAttribute("x", x); q.setAttribute("y", y); q.setAttribute("width", w); q.setAttribute("height", h); q.setAttribute("rx", 35) }
    else if (n.shape === "input_output") { q = el("polygon"); q.setAttribute("points", `${x + 15},${y} ${w / 2},${y} ${w / 2 - 15},${h / 2} ${x},${h / 2}`) }
    else if (n.shape === "database" || n.shape === "data_store") { q = el("path"); q.setAttribute("d", `M${x},${y + 10} C${x},${y - 8} ${w / 2},${y - 8} ${w / 2},${y + 10} V${h / 2 - 10} C${w / 2},${h / 2 + 8} ${x},${h / 2 + 8} ${x},${h / 2 - 10} Z M${x},${y + 10} C${x},${y + 28} ${w / 2},${y + 28} ${w / 2},${y + 10}`) }
    else if (n.shape === "document") { q = el("path"); q.setAttribute("d", `M${x},${y}H${w / 2}V${h / 2 - 12} Q${w / 4},${h / 2 + 8} 0,${h / 2 - 12} Q${-w / 4},${h / 2 + 8} ${x},${h / 2 - 12}Z`) }
    else if (n.shape === "preparation" || n.shape === "off_page") { q = el("polygon"); q.setAttribute("points", `${x + 18},${y} ${w / 2 - 18},${y} ${w / 2},0 ${w / 2 - 18},${h / 2} ${x + 18},${h / 2} ${x},0`) }
    else if (n.shape === "delay") { q = el("path"); q.setAttribute("d", `M${x},${y}H${w / 2 - 18} A${h / 2},${h / 2} 0 0 1 ${w / 2 - 18},${h / 2}H${x}Z`) }
    else { q = el("rect"); q.setAttribute("x", x); q.setAttribute("y", y); q.setAttribute("width", w); q.setAttribute("height", h); q.setAttribute("rx", n.shape === "subroutine" ? 3 : 10); if (n.shape === "subroutine") { q.setAttribute("stroke-dasharray", "8 4") } }
    q.classList.add("nodeShape"); q.setAttribute("fill", n.color); q.setAttribute("stroke", S.selNode === n.id ? "#2563eb" : "#334155"); q.setAttribute("stroke-width", S.selNode === n.id ? 3 : 2); g.appendChild(q);
    let t = el("text"); t.textContent = n.label.length > 23 ? n.label.slice(0, 22) + "…" : n.label; t.setAttribute("text-anchor", "middle"); t.setAttribute("dominant-baseline", "middle"); t.setAttribute("fill", n.textColor); t.classList.add("label"); g.appendChild(t)
}
function render(skipProperties = false) {
    view.setAttribute("transform", `translate(${S.panX} ${S.panY}) scale(${S.zoom})`); $("zoom").textContent = Math.round(S.zoom * 100) + "%"; edgesEl.innerHTML = ""; nodesEl.innerHTML = ""; preview.innerHTML = "";
    S.edges.forEach((e, i) => { let a = S.nodes.find(n => n.id === e.source), b = S.nodes.find(n => n.id === e.target); if (!a || !b) return; let [x1, y1] = edgePoint(a, b.x, b.y), [x2, y2] = edgePoint(b, a.x, a.y), l = document.createElementNS(svg.namespaceURI, "line"); l.setAttribute("x1", x1); l.setAttribute("y1", y1); l.setAttribute("x2", x2); l.setAttribute("y2", y2); l.classList.add("edge"); if (i === S.selEdge) l.classList.add("selected"); if (e.style === "dashed") l.setAttribute("stroke-dasharray", "10 7"); if (e.style === "dotted") l.setAttribute("stroke-dasharray", "3 5"); if (e.style === "thick") l.setAttribute("stroke-width", 4); if (e.dir === "forward" || e.dir === "both") l.setAttribute("marker-end", "url(#arr)"); if (e.dir === "backward" || e.dir === "both") l.setAttribute("marker-start", "url(#arrs)"); l.dataset.edge = i; edgesEl.appendChild(l); if (e.label) { let t = document.createElementNS(svg.namespaceURI, "text"); t.textContent = e.label; t.setAttribute("x", (x1 + x2) / 2); t.setAttribute("y", (y1 + y2) / 2 - 8); t.classList.add("edgeLabel"); t.dataset.edge = i; edgesEl.appendChild(t) } })
    if (S.connect) { let a = S.nodes.find(n => n.id === S.connect.id), [x1, y1] = edgePoint(a, S.connect.x, S.connect.y), l = document.createElementNS(svg.namespaceURI, "line"); l.setAttribute("x1", x1); l.setAttribute("y1", y1); l.setAttribute("x2", S.connect.x); l.setAttribute("y2", S.connect.y); l.classList.add("preview"); preview.appendChild(l) }
    S.nodes.forEach(n => { let g = document.createElementNS(svg.namespaceURI, "g"); g.classList.add("node"); g.dataset.node = n.id; g.setAttribute("transform", `translate(${n.x} ${n.y})`); shape(g, n); nodesEl.appendChild(g) }); code.value = markdown(); $("empty").style.display = S.nodes.length ? "none" : "grid"; if (!skipProperties) renderProps()
}
function renderProps() {
    let n = S.nodes.find(x => x.id === S.selNode), e = S.edges[S.selEdge]; if (n) { props.innerHTML = `<h3>Node Properties</h3><label>Label<input id="pl" value="${n.label}"></label><label>Shape<select id="ps">${TYPES ? TYPES.map(x => `<option value="${x[0]}" ${x[0] === n.shape ? "selected" : ""}>${x[1]}</option>`).join("") : ""}</select></label><div class="colors"><label>Fill<input id="pc" type="color" value="${n.color}"></label><label>Text<input id="pt" type="color" value="${n.textColor}"></label></div><button id="dn" class="danger">Delete Node</button><button id="dup">Duplicate</button>`; $("pl").oninput = x => { n.label = x.target.value; render(true) }; $("ps").onchange = x => { n.shape = x.target.value; render() }; $("pc").oninput = x => { n.color = x.target.value; render() }; $("pt").oninput = x => { n.textColor = x.target.value; render() }; $("dn").onclick = () => delNode(n.id); $("dup").onclick = () => dup(n.id) }
    else if (e) { props.innerHTML = `<h3>Arrow Properties</h3><label>Text on arrow<input id="el" value="${e.label}"></label><label>Direction<select id="ed"><option value="forward">Forward →</option><option value="backward">Backward ←</option><option value="both">Both ↔</option><option value="none">None —</option></select></label><label>Style<select id="es"><option>solid</option><option>dashed</option><option>dotted</option><option>thick</option></select></label><button id="de" class="danger">Delete Arrow</button>`; $("ed").value = e.dir; $("es").value = e.style; $("el").oninput = x => { e.label = x.target.value; render(true) }; $("ed").onchange = x => { e.dir = x.target.value; render() }; $("es").onchange = x => { e.style = x.target.value; render() }; $("de").onclick = () => { S.edges.splice(S.selEdge, 1); S.selEdge = null; render() } }
    else props.innerHTML = "<h3>Properties</h3><p>Select a node or arrow.</p>"
}
function delNode(id) { S.nodes = S.nodes.filter(n => n.id !== id); S.edges = S.edges.filter(e => e.source !== id && e.target !== id); S.selNode = null; render() }
function dup(id) { let n = S.nodes.find(x => x.id === id), c = { ...n, id: idNew(), x: n.x + 35, y: n.y + 35 }; S.nodes.push(c); S.selNode = c.id; render() }
function idNew() { return id() }
function add(shape, x, y) { let n = { id: id(), label: TYPE[shape].name, shape, color: TYPE[shape].color, textColor: "#111827", x, y }; S.nodes.push(n); S.selNode = n.id; S.selEdge = null; render() }
$("palette").innerHTML = TYPES.map(x => `<button class="shape" draggable="true" data-shape="${x[0]}"><i>${x[2]}</i>${x[1]}</button>`).join("");
document.querySelectorAll(".shape").forEach(b => b.ondragstart = e => e.dataTransfer.setData("shape", b.dataset.shape)); $("wrap").ondragover = e => e.preventDefault(); $("wrap").ondrop = e => { e.preventDefault(); let s = e.dataTransfer.getData("shape"); if (s) { let p = pt(e.clientX, e.clientY); add(s, p.x, p.y) } };
svg.onpointerdown = e => { let g = e.target.closest(".node"); if (g) { let n = S.nodes.find(x => x.id === g.dataset.node), p = pt(e.clientX, e.clientY); S.selNode = n.id; S.selEdge = null; if (S.mode === "connect") { S.connect = { id: n.id, x: p.x, y: p.y }; svg.setPointerCapture(e.pointerId) } else S.drag = { id: n.id, dx: p.x - n.x, dy: p.y - n.y }; render(); return } let edge = e.target.dataset.edge; if (edge != null) { S.selEdge = +edge; S.selNode = null; render() } else { S.selNode = null; S.selEdge = null; render() } };
svg.onpointermove = e => { let p = pt(e.clientX, e.clientY); if (S.connect) { S.connect.x = p.x; S.connect.y = p.y; renderCanvasOnly() } else if (S.drag) { let n = S.nodes.find(x => x.id === S.drag.id); n.x = p.x - S.drag.dx; n.y = p.y - S.drag.dy; renderCanvasOnly() } };
svg.onpointerup = e => { if (S.connect) { let p = pt(e.clientX, e.clientY), t = [...S.nodes].reverse().find(n => Math.abs(n.x - p.x) < 70 && Math.abs(n.y - p.y) < 35); if (t && t.id !== S.connect.id) S.edges.push({ source: S.connect.id, target: t.id, label: "", dir: "forward", style: "solid" }); S.connect = null; S.mode = "select"; document.querySelectorAll(".mode").forEach(x => x.classList.toggle("active", x.dataset.mode === "select")); render() } S.drag = null };
function renderCanvasOnly() { view.setAttribute("transform", `translate(${S.panX} ${S.panY}) scale(${S.zoom})`); render() }
svg.onwheel = e => { e.preventDefault(); S.zoom = Math.max(.3, Math.min(3, S.zoom * (e.deltaY < 0 ? 1.1 : .9))); render() };
document.querySelectorAll(".mode").forEach(b => b.onclick = () => { S.mode = b.dataset.mode; document.querySelectorAll(".mode").forEach(x => x.classList.toggle("active", x === b)) });
$("dir").onchange = e => { S.dir = e.target.value; render() }; $("snap").onclick = () => { S.nodes.forEach(n => { n.x = Math.round(n.x / 20) * 20; n.y = Math.round(n.y / 20) * 20 }); render() }; $("plus").onclick = () => { S.zoom = Math.min(3, S.zoom * 1.15); render() }; $("minus").onclick = () => { S.zoom = Math.max(.3, S.zoom / 1.15); render() };
$("fit").onclick = fit; $("layout").onclick = layout;
function fit() { if (!S.nodes.length) { S.zoom = 1; S.panX = S.panY = 0; render(); return } let minx = Math.min(...S.nodes.map(n => n.x)) - 100, maxx = Math.max(...S.nodes.map(n => n.x)) + 100, miny = Math.min(...S.nodes.map(n => n.y)) - 80, maxy = Math.max(...S.nodes.map(n => n.y)) + 80, w = svg.clientWidth, h = svg.clientHeight; S.zoom = Math.min(1.6, Math.max(.4, Math.min(w / (maxx - minx), h / (maxy - miny)))); S.panX = w / 2 - (minx + maxx) / 2 * S.zoom; S.panY = h / 2 - (miny + maxy) / 2 * S.zoom; render() }
function layout() { S.nodes.forEach((n, i) => { n.x = 160 + (i % 4) * 190; n.y = 120 + Math.floor(i / 4) * 120 }); fit(); render() }
document.onkeydown = e => { if (["INPUT", "TEXTAREA", "SELECT"].includes(document.activeElement.tagName)) return; if (e.key === "Delete" || e.key === "Backspace") { if (S.selNode) delNode(S.selNode); else if (S.selEdge != null) { S.edges.splice(S.selEdge, 1); S.selEdge = null; render() } } if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "d" && S.selNode) { e.preventDefault(); dup(S.selNode) } };
function dl(name, data, type) { let u = URL.createObjectURL(new Blob([data], { type })), a = document.createElement("a"); a.href = u; a.download = name; document.body.appendChild(a); a.click(); setTimeout(() => { URL.revokeObjectURL(u); a.remove() }, 1000) }
$("md").onclick = () => dl("mermaid-diagram.md", markdown(), "text/markdown"); $("copy").onclick = () => navigator.clipboard.writeText(markdown()).then(() => toast("Copied"));
$("svg").onclick = () => { let c = svg.cloneNode(true); c.setAttribute("xmlns", "http://www.w3.org/2000/svg"); dl("mermaid-diagram.svg", new XMLSerializer().serializeToString(c), "image/svg+xml") };
$("png").onclick = () => { let c = svg.cloneNode(true); c.setAttribute("xmlns", "http://www.w3.org/2000/svg"); let u = URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(c)], { type: "image/svg+xml" })), im = new Image(); im.onload = () => { let cv = document.createElement("canvas"); cv.width = svg.clientWidth; cv.height = svg.clientHeight; cv.getContext("2d").drawImage(im, 0, 0); cv.toBlob(b => dl("mermaid-diagram.png", b, "image/png")); URL.revokeObjectURL(u) }; im.src = u };
$("theme").onclick = () => { S.dark = !S.dark; document.body.classList.toggle("dark", S.dark); $("theme").textContent = S.dark ? "☀" : "☾"; localStorage.theme = S.dark ? "dark" : "light" };
$("help").onclick = () => helpBox.showModal(); $("new").onclick = () => { if (confirm("Start a new diagram?")) { S.nodes = []; S.edges = []; S.selNode = null; S.selEdge = null; render() } };
$("open").onchange = async e => { let f = e.target.files[0]; if (!f) return; importMd(await f.text()) };
function importMd(t) { let b = t.match(/```mermaid\s*([\s\S]*?)```/i), s = (b ? b[1] : t).trim(), m = s.match(/flowchart\s+(TB|BT|LR|RL)/i); if (m) S.dir = m[1]; let map = new Map(), es = []; for (let line of s.split(/\r?\n/).map(x => x.trim())) { if (!line || /^flowchart|^style/i.test(line)) continue; let e = line.match(/^(\w+)\s+(.+?)\s+(\w+)$/); if (e && /--|==|-\./.test(e[2])) { let a = e[2].match(/<-->|<--|-->|<==>|<==|==>|---|-\.-|-\.\->/); if (a) es.push({ source: e[1], target: e[3], label: (e[2].match(/\|([^|]*)\|/) || [])[1] || "", dir: a[0].includes("<") && a[0].includes(">") ? "both" : a[0].startsWith("<") ? "backward" : a[0].includes(">") ? "forward" : "none", style: a[0].includes(".") ? "dotted" : a[0].includes("=") ? "thick" : "solid" }); continue } let n = line.match(/^(\w+)\s+(.+)$/); if (!n) continue; let shape = "process", label = n[2]; if (/^\(\[".*"\]\)$/.test(label)) shape = "start_end"; else if (/^\{".*"\}$/.test(label)) shape = "decision"; else if (/^\[\(".*"\)\]$/.test(label)) shape = "database"; else if (/^\[".*"\]$/.test(label)) shape = "process"; label = label.replace(/^[^\[]*/, "").replace(/[\[\]\(\)\{\}"\/]/g, "").trim() || n[1]; map.set(n[1], { id: n[1], label, shape, color: TYPE[shape].color, textColor: "#111827", x: 160 + map.size % 4 * 190, y: 120 + Math.floor(map.size / 4) * 120 }) } es.forEach(e => { [e.source, e.target].forEach(x => { if (!map.has(x)) map.set(x, { id: x, label: x, shape: "process", color: TYPE.process.color, textColor: "#111827", x: 160, y: 120 + map.size * 100 }) }) }); if (!map.size) return toast("No Mermaid flowchart found."); S.nodes = [...map.values()]; S.edges = es; S.next = S.nodes.length; S.selNode = S.nodes[0]?.id || null; render(); fit() }
function toast(x) { let t = $("toast"); t.textContent = x; t.classList.add("show"); setTimeout(() => t.classList.remove("show"), 1500) }
if (localStorage.theme === "dark") { S.dark = true; document.body.classList.add("dark"); $("theme").textContent = "☀" } render();